apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubenet-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubenet
    spec:
      containers:
        - name: k8s-web
          image: kubenet:latest
          ports:
            - containerPort: 80
          env:
          - name: AI_KEY
            value: 903ajd4f-g29s-44p7-pol7-whatever
---
apiVersion: v1
kind: Service
metadata:
  name: kubenet-service
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: kubenet
  type: LoadBalancer
